import { operations } from "./filterOperations";

export const FIELD_ROLE_OPTIONS = [{
  key: "metric",
  label: "Metric",
  value: "metric",
}, {
  key: "dimension",
  label: "Dimension",
  value: "dimension",
}, {
  key: "date",
  label: "Date",
  value: "date",
}];

export const FIELD_AGGREGATION_OPTIONS = operations.filter((operation) => (
  ["none", "count", "sum", "avg", "min", "max"].includes(operation.value)
));

const ROLE_ORDER = {
  date: 0,
  metric: 1,
  dimension: 2,
};

export function getFieldTypeColor(type) {
  if (type === "date") return "secondary";
  if (type === "number") return "primary";
  if (type === "string") return "success";
  if (type === "boolean") return "warning";
  return "default";
}

export function formatFieldPath(fieldPath) {
  return String(fieldPath || "")
    .replace(/^root\[\]\.?/, "")
    .replace(/^root\./, "")
    .replace(/\[\]/g, "")
    .trim();
}

export function createFieldLabel(fieldPath) {
  return formatFieldPath(fieldPath)
    .replace(/\./g, " ")
    .replace(/_/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

export function getDefaultAggregation(role, fieldType) {
  if (role !== "metric") {
    return "none";
  }

  if (fieldType === "boolean") {
    return "count";
  }

  return "sum";
}

export function normalizeEditableFieldsMetadata(fieldsMetadata = []) {
  if (!Array.isArray(fieldsMetadata)) {
    return [];
  }

  return fieldsMetadata.map((field) => {
    const fieldId = field.id || field.legacyPath;
    const role = field.role || "dimension";

    return {
      ...field,
      id: fieldId,
      legacyPath: field.legacyPath || fieldId,
      name: field.name || formatFieldPath(fieldId),
      label: field.label || createFieldLabel(fieldId),
      description: field.description || "",
      previewSample: Array.isArray(field.previewSample) ? field.previewSample : [],
      role,
      aggregation: role === "metric"
        ? (field.aggregation || getDefaultAggregation(role, field.type))
        : "none",
      enabled: field.enabled !== false,
      autoGenerated: field.autoGenerated !== false,
      excludeFromCharts: field.excludeFromCharts === true,
      missing: field.missing === true,
    };
  });
}

export function sortDatasetFieldsMetadata(fieldsMetadata = []) {
  return [...normalizeEditableFieldsMetadata(fieldsMetadata)].sort((left, right) => {
    if ((left.missing === true) !== (right.missing === true)) {
      return left.missing === true ? 1 : -1;
    }

    const leftRoleOrder = ROLE_ORDER[left.role] ?? 99;
    const rightRoleOrder = ROLE_ORDER[right.role] ?? 99;
    if (leftRoleOrder !== rightRoleOrder) {
      return leftRoleOrder - rightRoleOrder;
    }

    return (left.label || left.id).localeCompare(right.label || right.id);
  });
}

export function buildFieldOptionsFromMetadata(fieldsMetadata = []) {
  return sortDatasetFieldsMetadata(fieldsMetadata)
    .filter((field) => field.id && field.missing !== true)
    .map((field) => ({
      key: field.id,
      text: field.label || createFieldLabel(field.id),
      rawField: field.legacyPath || field.id,
      value: field.legacyPath || field.id,
      type: field.type,
      role: field.role,
      enabled: field.enabled !== false,
      isObject: !String(field.legacyPath || field.id).includes("[]"),
      label: {
        style: { width: 55, textAlign: "center" },
        content: field.type || "unknown",
        size: "mini",
        color: getFieldTypeColor(field.type),
      },
    }));
}

export function buildFieldOptionsFromSchema(fieldsSchema = {}) {
  return Object.keys(fieldsSchema).map((fieldPath) => ({
    key: fieldPath,
    text: formatFieldPath(fieldPath),
    rawField: fieldPath,
    value: fieldPath,
    type: fieldsSchema[fieldPath],
    isObject: fieldPath.indexOf("[]") === -1,
    label: {
      style: { width: 55, textAlign: "center" },
      content: fieldsSchema[fieldPath] || "unknown",
      size: "mini",
      color: getFieldTypeColor(fieldsSchema[fieldPath]),
    },
  }));
}

export function buildDatasetFieldOptions(dataset) {
  if (dataset?.fieldsMetadata?.length > 0) {
    return buildFieldOptionsFromMetadata(dataset.fieldsMetadata);
  }

  if (dataset?.fieldsSchema) {
    return buildFieldOptionsFromSchema(dataset.fieldsSchema);
  }

  return [];
}
