const builder = require("./builder");
const googleConnector = require("../../modules/googleConnector");
const db = require("../../models/models");

const template = (configuration = {}, dashboardOrder = 1) => ({
  "Charts": [
    {
      "name": "Users",
      "type": "line",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 2,
      "dashboardOrder": dashboardOrder,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpichart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": true,
      "Datasets": [
        {
          "fillColor": "rgba(81, 186, 176, 0.36)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].newUsers": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": {
            "joins": []
          },
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].newUsers",
          "yAxisOperation": "none",
          "dateField": "root[].date",
          "datasetColor": "rgba(81, 186, 176, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "New users",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "newUsers",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "connection_id": 678,
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
              "Connection": 678
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].activeUsers": "date"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].activeUsers",
          "yAxisOperation": "none",
          "dateField": "root[].date",
          "datasetColor": "rgba(154, 226, 95, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Active users",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": "accounts/48182378",
                "propertyId": "properties/390996630",
                "filters": [],
                "metrics": "activeUsers",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
              "Connection": 678
            }
          ]
        }
      ],
      "tid": 0
    },
    {
      "name": "Users KPIs",
      "type": "line",
      "subType": "AddTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 1,
      "dashboardOrder": dashboardOrder + 1,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpi",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].newUsers": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].newUsers",
          "yAxisOperation": "count",
          "dateField": "root[].date",
          "datasetColor": "rgba(81, 186, 176, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "New users",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "newUsers",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].activeUsers": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": {
            "joins": []
          },
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].activeUsers",
          "yAxisOperation": "count",
          "dateField": "root[].date",
          "datasetColor": "rgba(154, 226, 95, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Active users",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 1,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "activeUsers",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 1
    },
    {
      "name": "Bounce rate",
      "type": "line",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 1,
      "dashboardOrder": dashboardOrder + 2,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpi",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].bounceRate": "string"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].bounceRate",
          "xAxisOperation": null,
          "yAxis": "root[].bounceRate",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(81, 186, 176, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Bounce rate",
          "pointRadius": null,
          "formula": "{val * 100}%",
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "bounceRate",
                "startDate": "30daysAgo",
                "endDate": "yesterday"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 2
    },
    {
      "name": "Events",
      "type": "line",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 2,
      "dashboardOrder": dashboardOrder + 3,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpichart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": true,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].eventCount": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].eventCount",
          "yAxisOperation": "none",
          "dateField": "root[].date",
          "datasetColor": "rgba(255, 117, 151, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Total events",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "eventCount",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].date": "date",
            "root[].activeUsers": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].date",
          "xAxisOperation": null,
          "yAxis": "root[].activeUsers",
          "yAxisOperation": "none",
          "dateField": "root[].date",
          "datasetColor": "rgba(150, 158, 203, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Conversions",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 1,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "conversions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "date"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 3
    },
    {
      "name": "Conversions",
      "type": "line",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 1,
      "dashboardOrder": dashboardOrder + 4,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpi",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].conversions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].conversions",
          "xAxisOperation": null,
          "yAxis": "root[].conversions",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(150, 158, 203, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Conversions",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "conversions",
                "startDate": "30daysAgo",
                "endDate": "yesterday"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 4
    },
    {
      "name": "Engagement",
      "type": "line",
      "subType": "timeseries",
      "public": false,
      "shareable": false,
      "chartSize": 1,
      "dashboardOrder": dashboardOrder + 5,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "kpi",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].userEngagementDuration": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": {
            "joins": []
          },
          "connection_id": null,
          "query": null,
          "xAxis": "root[].userEngagementDuration",
          "xAxisOperation": null,
          "yAxis": "root[].userEngagementDuration",
          "yAxisOperation": "none",
          "dateField": "",
          "datasetColor": "rgba(251, 239, 137, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Duration (s)",
          "pointRadius": null,
          "formula": "",
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "userEngagementDuration",
                "startDate": "30daysAgo",
                "endDate": "yesterday"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].engagementRate": "string"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].engagementRate",
          "xAxisOperation": null,
          "yAxis": "root[].engagementRate",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(110, 230, 245, 1)",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Engagement rate",
          "pointRadius": null,
          "formula": "{val * 100}%",
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 1,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "engagementRate",
                "startDate": "30daysAgo",
                "endDate": "yesterday"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 5
    },
    {
      "name": "New users by Country",
      "type": "bar",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 2,
      "dashboardOrder": dashboardOrder + 7,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": true,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "chart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "showAll",
      "stacked": false,
      "horizontal": true,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": [
            "rgba(81, 186, 176, 1)",
            "rgba(154, 226, 95, 1)",
            "rgba(255, 117, 151, 1)",
            "rgba(150, 158, 203, 1)",
            "rgba(251, 239, 137, 1)",
            "rgba(110, 230, 245, 1)",
            "rgba(187, 134, 252, 1)",
            "rgba(255, 196, 121, 1)",
            "rgba(66, 165, 245, 1)",
            "rgba(240, 126, 124, 1)"
          ],
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].country": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].country",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(255, 255, 255, 1)",
          "fill": false,
          "multiFill": true,
          "dateFormat": null,
          "legend": "Sessions",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": "",
          "averageByTotal": false,
          "order": 0,
          "maxRecords": 10,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "country"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 7
    },
    {
      "name": "Top sources",
      "type": "bar",
      "subType": "lcTimeseries",
      "public": false,
      "shareable": false,
      "chartSize": 2,
      "dashboardOrder": dashboardOrder + 8,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": true,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "chart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": true,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": [
            "rgba(81, 186, 176, 1)",
            "rgba(154, 226, 95, 1)",
            "rgba(255, 117, 151, 1)",
            "rgba(150, 158, 203, 1)",
            "rgba(251, 239, 137, 1)"
          ],
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].sessionSource": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].sessionSource",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(255, 255, 255, 1)",
          "fill": false,
          "multiFill": true,
          "dateFormat": null,
          "legend": "Sessions",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": "desc",
          "averageByTotal": false,
          "order": 0,
          "maxRecords": 10,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "sessionSource"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 8
    },
    {
      "name": "Sessions by device",
      "type": "doughnut",
      "subType": "timeseries",
      "public": false,
      "shareable": false,
      "chartSize": 1,
      "dashboardOrder": dashboardOrder + 9,
      "displayLegend": true,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "chart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": [
            "rgba(81, 186, 176, 1)",
            "rgba(154, 226, 95, 1)"
          ],
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].deviceCategory": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].deviceCategory",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "none",
          "dateField": null,
          "datasetColor": "rgba(255, 255, 255, 1)",
          "fill": false,
          "multiFill": true,
          "dateFormat": null,
          "legend": "Dataset #1",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "deviceCategory"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 8
    },
    {
      "name": "Detailed sessions view",
      "type": "table",
      "subType": "timeseries",
      "public": false,
      "shareable": false,
      "chartSize": 3,
      "dashboardOrder": dashboardOrder + 10,
      "displayLegend": false,
      "pointRadius": null,
      "dataLabels": false,
      "startDate": null,
      "endDate": null,
      "dateVarsFormat": null,
      "includeZeros": true,
      "currentEndDate": false,
      "fixedStartDate": false,
      "timeInterval": "day",
      "autoUpdate": 86400,
      "draft": false,
      "mode": "chart",
      "maxValue": null,
      "minValue": null,
      "disabledExport": null,
      "onReport": false,
      "xLabelTicks": "default",
      "stacked": false,
      "horizontal": false,
      "showGrowth": false,
      "Datasets": [
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].sessionCampaignName": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].sessionCampaignName",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "count",
          "dateField": null,
          "datasetColor": "#17BECF",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Campaigns",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "sessionCampaignName"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].sessionMedium": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].sessionMedium",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "count",
          "dateField": null,
          "datasetColor": "#7F7F7F",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Mediums",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "sessionMedium"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].sessionDefaultChannelGroup": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].sessionDefaultChannelGroup",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "count",
          "dateField": null,
          "datasetColor": "#7F7F7F",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Channels",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "sessionDefaultChannelGroup"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        },
        {
          "fillColor": "rgba(0,0,0,0)",
          "patterns": [],
          "conditions": null,
          "fieldsSchema": {
            "root[].sessionSource": "string",
            "root[].sessions": "number"
          },
          "excludedFields": null,
          "groups": null,
          "columnsOrder": null,
          "configuration": null,
          "joinSettings": null,
          "connection_id": null,
          "query": null,
          "xAxis": "root[].sessionSource",
          "xAxisOperation": null,
          "yAxis": "root[].sessions",
          "yAxisOperation": "count",
          "dateField": null,
          "datasetColor": "#1F77B4",
          "fill": false,
          "multiFill": false,
          "dateFormat": null,
          "legend": "Sources",
          "pointRadius": null,
          "formula": null,
          "groupBy": null,
          "sort": null,
          "averageByTotal": false,
          "order": 0,
          "maxRecords": null,
          "DataRequests": [
            {
              "headers": null,
              "body": "null",
              "conditions": null,
              "configuration": {
                "accountId": configuration.accountId,
                "propertyId": configuration.propertyId,
                "filters": [],
                "metrics": "sessions",
                "startDate": "30daysAgo",
                "endDate": "yesterday",
                "dimensions": "sessionSource"
              },
              "method": null,
              "route": null,
              "useGlobalHeaders": true,
              "query": null,
              "pagination": false,
              "items": "items",
              "itemsLimit": 0,
              "offset": "offset",
              "paginationField": null,
              "template": null,
            }
          ]
        }
      ],
      "tid": 9
    }
  ],
  "Connections": [
    {
      "host": null,
      "dbName": null,
      "port": null,
      "username": null,
      "password": null,
      "options": null,
      "connectionString": "null",
      "authentication": null,
      "firebaseServiceAccount": null,
      "name": "Google Analytics - GA4",
      "type": "googleAnalytics",
      "subType": "googleAnalytics",
      "active": true,
      "srv": false
    }
  ]
});

module.exports.template = template;

module.exports.build = async (projectId, {
  configuration, charts, connection_id,
}, dashboardOrder) => {
  if (!configuration || !connection_id) return Promise.reject("Missing required parameters");

  let checkErrored = false;
  const connection = await db.Connection.findOne({
    where: { id: connection_id },
    include: [{ model: db.OAuth }]
  });

  const dataRequest = {
    configuration: {
      accountId: configuration.accountId,
      propertyId: configuration.propertyId,
      viewId: configuration.viewId,
      startDate: "30daysAgo",
      endDate: "yesterday",
      metrics: "ga:users",
    },
  };

  try {
    await googleConnector.getAnalytics(connection.OAuth.refreshToken, dataRequest);
  } catch (error) {
    checkErrored = true;
  }

  if (!connection_id && checkErrored) {
    return Promise.reject(new Error("Request cannot be authenticated"));
  }

  return builder(projectId, configuration, dashboardOrder, template, charts, connection_id)
    .catch((err) => {
      if (err && err.message) {
        return Promise.reject(err.message);
      }
      return Promise.reject(err);
    });
};
