module.exports = {
  CAN_CREATE_PROJECT: "CAN_CREATE_PROJECT",
  CAN_CREATE_CONNECTION: "CAN_CREATE_CONNECTION",
  CAN_CREATE_CHART: "CAN_CREATE_CHART",
  CAN_CHANGE_AUTOUPDATE: "CAN_CHANGE_AUTOUPDATE",
  CAN_INVITE_MEMBERS: "CAN_INVITE_MEMBERS",
  CAN_USE_DATA: "CAN_USE_DATA",
};
