import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    globals: true,
    include: [
      "tests/unit/chartImageAccess.test.js",
      "tests/unit/chartImageAuthentication.test.js",
      "tests/unit/chartImageController.test.js",
      "tests/unit/chartImageMetadata.test.js",
      "tests/unit/chartImageObservability.test.js",
      "tests/unit/chartImageRequest.test.js",
      "tests/unit/chartImageRenderer.test.js",
      "tests/unit/dataApiAccess.test.js",
      "tests/unit/dataApiContracts.test.js",
      "tests/unit/dataApiMigrations.test.js",
      "tests/unit/datasetData.test.js",
      "tests/unit/embeddedChartPayload.test.js",
      "tests/unit/echartsCompiler.test.js",
      "tests/unit/kpiReview.test.js",
      "tests/unit/legacyChartDataPreparedData.test.js",
      "tests/unit/logoUploadSecurity.test.js",
      "tests/unit/migrateHorizontalBars.test.js",
      "tests/unit/nodemail.passwordReset.test.js",
      "tests/unit/observationPeriodCorpus.test.js",
      "tests/unit/observations.test.js",
      "tests/unit/periodEvaluator.test.js",
      "tests/unit/periodObservationPersistence.test.js",
      "tests/unit/platformSettings.test.js",
      "tests/unit/preparedSnapshots.test.js",
      "tests/unit/replaySynthbrewPeriods.test.js",
      "tests/unit/responsiveLayout.test.js",
      "tests/unit/scheduleWeekdays.test.js",
      "tests/unit/visualizationCompilers.test.js",
      "tests/unit/visualizationFilters.test.js",
      "tests/unit/visualizationPreparedData.test.js",
      "tests/unit/visualizationTime.test.js",
      "tests/unit/verifyDataApiKey.test.js",
    ],
    maxWorkers: 2,
    pool: "forks",
  },
});
